/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : Status,
  'staffId' : bigint,
  'clientName' : string,
  'serviceId' : bigint,
  'datetime' : Time,
}
export interface CustomerPhoto {
  'id' : bigint,
  'customerName' : string,
  'review' : string,
  'timestamp' : Time,
  'photo' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface Service {
  'id' : bigint,
  'duration' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : number,
}
export interface Staff {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'role' : string,
}
export type Status = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomerPhoto' : ActorMethod<[string, ExternalBlob, string], undefined>,
  'addService' : ActorMethod<
    [string, string, bigint, number, string],
    undefined
  >,
  'addStaffMember' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[string, bigint, bigint, Time], bigint>,
  'deleteCustomerPhoto' : ActorMethod<[bigint], undefined>,
  'editCustomerPhotoReview' : ActorMethod<[bigint, string], undefined>,
  'getAppointment' : ActorMethod<[bigint], Appointment>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerPhotoReviews' : ActorMethod<[], Array<string>>,
  'getCustomerPhotos' : ActorMethod<[], Array<CustomerPhoto>>,
  'getPendingAppointments' : ActorMethod<[], Array<Appointment>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getServicesByCategory' : ActorMethod<[string], Array<Service>>,
  'getStaffMembers' : ActorMethod<[], Array<Staff>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppointmentStatus' : ActorMethod<[bigint, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];